### ISSUE TITLE
CoreIR Rewrite Rule + Application Checklist 

### ISSUE THREAD

**Issue by joyliu37** [StanfordAHA/Halide-to-Hardware_archive#43]
## General Issue
- [ ] Stride Conv with odd row size has line buffer size incorrect 
- [ ] Using PyCoreIR instead of pure json generation
## Image Processing Applications
- [x] 3x3 conv
- [x] harris
- [ ] strided conv
- [ ] camera pipeline
## NN Processing Applications
- [x] UNet layer
- [ ] UNet psum buffer ??
- [ ] MobileNet with line buffer and double buffer ??
